development:
  sessions:
    default:
      database: devices_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    types:
      database: types_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
test:
  sessions:
    default:
      database: devices_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    types:
      database: types_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
