development:
  sessions:
    default:
      database: devices_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    types:
      database: types_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    products:
      database: products_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    jobs:
      database: jobs_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
test:
  sessions:
    default:
      database: devices_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    types:
      database: types_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    products:
      database: products_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    jobs:
      database: jobs_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_DEVICES_URL'] %>
    people:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] %>
    types:
      uri: <%= ENV['MONGOLAB_TYPES_URL'] %>
    products:
      uri: <%= ENV['MONGOLAB_PRODUCTS_URL'] %>
    jobs:
      uri: <%= ENV['MONGOLAB_JOBS_URL'] %>
  options:
