<<<<<<< HEAD
development:
  host: localhost
  database: devices_development

test:
  host: localhost
  database: devices_test
=======
defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: device_development

test:
  <<: *defaults
  database: device_test
>>>>>>> a94ab928ffed209bca7c3d87982a12be9974a750

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
<<<<<<< HEAD
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
=======
>>>>>>> a94ab928ffed209bca7c3d87982a12be9974a750
