pagination:
  per: 25
  max_per: 100
scopes:
  read:
    - resources
    - resources:read
    - devices
    - devices:control
    - devices:read
  write:
    - resources
    - devices
  control:
    - resources
    - devices
    - devices:control
  history_read:
    - resources
    - resources:read
    - histories:read
  consumptions:
    - resources
    - consumptions
  consumptions_read:
    - resources
    - resources:read
    - consumptions
    - consumptions:read
