device:
  host: <%= device_host = "https://device.lelylan.com" %>
  uri: <%= "#{device_host}/devices/closet-dimmer" %>
  another:
    uri: <%= "#{device_host}/devices/another-closet-dimmer" %>
type:
  host: <%= type_host = "https://type.lelylan.com" %>
  uri: <%= "#{type_host}/types/dimmer" %>
  another:
    uri: <%= "#{type_host}/types/another-dimmer" %>

physical:
  host: <%= physical_host = "https://node.lelylan.com" %>
  uri: <%= "#{physical_host}/devices/physical-dimmer" %>
  another: 
    uri: <%= "#{physical_host}/devices/another-physical-dimmer" %>

user: 
  host: <%= people_host = "https://people.lelylan.com" %>
  auth: <%= "#{people_host}/authentication" %>
  uri: <%= "#{people_host}/users/alice" %>
  email: 'alice@example.com'
  password: 'example'
  another: 
    uri: <%= "#{people_host}/users/bob" %>
    email: 'bob@example.com'

properties:
  status:
    uri: <%= status_uri = "#{type_host}/properties/status" %> 
    name: 'Status'
    default_value: 'off'
    new_value: 'on'
  intensity:
    uri: <%= intensity_uri = "#{type_host}/properties/intensity" %> 
    name: 'Intensity'
    default_value: '0.0'
    new_value: '100.0'
  another:
    uri: <%= "#{type_host}/properties/another-property" %>
    value: '25.0'

functions:
  set_status:
    uri: <%= set_status_uri = "#{type_host}/functions/set-status" %>
  set_intensity:
    uri: <%= set_intensity_uri = "#{type_host}/functions/set-intensity" %> 
  another:
    uri: <%= "#{type_host}/functions/another-function" %>

consumptions:
  instantaneous:
    uri: <%= "#{device_host}/consumptions/instantaneous" %>
  durational:
    uri: <%= "#{device_host}/consumptions/durational" %>

history:
  uri: <%= "#{device_host}/histories/set_intensity" %>

validation:
  uri:
    valid: 'http://example.com'
    not_valid: 'example'
